services:

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2
    restart: always

    ports:
      - "1883:1883"
      - "9001:9001"

    volumes:
      - ./runtime/mosquitto/config:/mosquitto/config
      - ./runtime/mosquitto/data:/mosquitto/data
      - ./runtime/mosquitto/log:/mosquitto/log

    networks:
      - iot


  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: ghcr.io/koenkk/zigbee2mqtt:2.10.0
    restart: always

    depends_on:
      - mosquitto

    ports:
      - "8080:8080"

    volumes:
      - ./runtime/zigbee2mqtt:/app/data

    environment:
      - TZ=Europe/Rome

    networks:
      - iot


  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:2026.5
    restart: always

    depends_on:
      - mosquitto

    ports:
      - "8123:8123"

    volumes:
      - ./runtime/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro

    environment:
      - TZ=Europe/Rome

    privileged: true

    networks:
      - iot


  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.42.0-alpine
    restart: always

    ports:
      - "9000:9000"
      - "9443:9443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runtime/portainer:/data

    networks:
      - iot


networks:
  iot:
    driver: bridge