services:

  zigbee2mqtt:
    image: ghcr.io/koenkk/zigbee2mqtt:2.12
    container_name: zigbee2mqtt
    restart: unless-stopped

    user: ${USER}:${GROUP}

    ports:
      - "8080:8080"

    volumes:
      - ${ROOT}/runtime/zigbee2mqtt:/app/data

    networks:
      - mqtt-net

networks:
  mqtt-net:
    external: true

      