- sensor:
  - name: "Deco clients (office)"
    unique_id: deco_clients_office
    icon: mdi:devices
    unit_of_measurement: "clients"
    state: >
      {{ states('sensor.office_deco_connected_clients') | int(0) }}

  - name: "Deco clients (study room)"
    unique_id: deco_clients_study_room
    icon: mdi:devices
    unit_of_measurement: "clients"
    state: >
      {{ states('sensor.study_room_deco_connected_clients') | int(0) }}
