- device_tracker:
    - name: "Tracker Wi-Fi Galaxy S21"
      icon: mdi:cellphone
      in_zones: >
        {% if is_state('binary_sensor.192_168_1_120', 'on') %}
          ['zone.home']
        {% else %}
          []
        {% endif %}

    - name: "Tracker Wi-Fi Galaxy A32"
      icon: mdi:cellphone
      in_zones: >
        {% if is_state('binary_sensor.192_168_1_121', 'on') %}
          ['zone.home']
        {% else %}
          []
        {% endif %}
