services:

  dockge:
    image: louislam/dockge:1
    container_name: dockge
    restart: unless-stopped

    ports:
      - "5001:5001"

    environment:
      - DOCKGE_STACKS_DIR=/workspace/stacks

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ROOT}/runtime/dockge:/app/data
      - ${ROOT}:/workspace