services:

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:2026.5
    container_name: homeassistant
    restart: unless-stopped

    user: ${USER}:${GROUP}

    ports:
      - "8123:8123"

    volumes:
      - ${ROOT}/runtime/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
