services:

  npm:
    image: jc21/nginx-proxy-manager:2
    container_name: nginx-proxy-manager
    restart: unless-stopped

    ports:
      - "80:80"
      - "81:81"
      - "443:443"

    volumes:
      - ${ROOT}/runtime/npm/data:/data
      - ${ROOT}/runtime/npm/letsencrypt:/etc/letsencrypt
