- platform: integration
  source: sensor.power_grid_import
  name: Energy Grid Import
  unit_prefix: k
  unit_time: h
  method: trapezoidal
  round: 3

- platform: integration
  source: sensor.power_grid_export
  name: Energy Grid Export
  unit_prefix: k
  unit_time: h
  method: trapezoidal
  round: 3

- platform: integration
  source: sensor.power_solar
  name: Energy Solar
  unit_prefix: k
  unit_time: h
  method: trapezoidal
  round: 3

- platform: integration
  source: sensor.power_home
  name: Energy Home
  unit_prefix: k
  unit_time: h
  method: trapezoidal
  round: 3

