services:

  adguard:
    container_name: adguard
    image: adguard/adguardhome:v0.107.76
    restart: always

    network_mode: host

    volumes:
      - ./runtime/adguard/work:/opt/adguardhome/work
      - ./runtime/adguard/conf:/opt/adguardhome/conf