services:

  adguard:
    container_name: adguard
    image: adguard/adguardhome:latest
    restart: always

    network_mode: host

    volumes:
      - ./runtime/adguard/work:/opt/adguardhome/work
      - ./runtime/adguard/conf:/opt/adguardhome/conf