services:

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    restart: unless-stopped
    
    user: ${USER}:${GROUP}
    
    ports:
      - "8086:8086"

    volumes:
      - ${ROOT}/runtime/influxdb/data:/var/lib/influxdb2
      - ${ROOT}/runtime/influxdb/config:/etc/influxdb2

