- sensor:
    name: "ASW3000H-S2 Inverter Raw"
    command: "curl -k -s 'https://192.168.1.105/getdev.cgi?device=2'"
    scan_interval: 20
    value_template: "{{ value_json.inv[0].isn | default('unknown') }}"
    json_attributes:
      - inv

- sensor:
    name: "ASW3000H-S2 Meter Raw"
    command: "sleep 5; curl -k -s 'https://192.168.1.105/getdev.cgi?device=3'"
    scan_interval: 20
    value_template: "{{ value_json.sn }}"
    json_attributes:
      - mod
      - enb
      - exp_m
      - regulate
      - enb_PF
      - target_PF
      - total_pac
      - total_fac
      - meter_pac
      - sn
      - manufactory
      - type
      - name
      - model
      - abs
      - abs_offset
      - sec_enb

- sensor:
    name: "ASW3000-S-G2 Inverter Raw"
    command: "curl -k -s 'https://192.168.1.106/getdev.cgi?device=2'"
    scan_interval: 20
    value_template: "{{ value_json.inv[0].isn | default('unknown') }}"
    json_attributes:
      - inv
