api_version: 2
host: influxdb
port: 8086
token: super-secret-token
organization: home
bucket: homeassistant
include:
  entities:
    - sensor.roof_sensor_temperature
    - sensor.first_floor_sensor_temperature
    - sensor.garden_sensor_temperature
    - sensor.ground_floor_sensor_temperature
    - sensor.roof_sensor_humidity
    - sensor.first_floor_sensor_humidity
    - sensor.garden_sensor_humidity
    - sensor.ground_floor_sensor_humidity
    - sensor.light_sensor_illuminance
    - sensor.power_solar
    - sensor.power_home
    - sensor.power_grid_import
    - sensor.power_grid_export
    - sensor.energy_solar
    - sensor.energy_home
    - sensor.energy_grid_import
    - sensor.energy_grid_export
    - sensor.heater_on_numeric    
    
    
