state_garden:
  name: State garden
  options:
    - "script.garden_off"
    - "script.garden_soft"
    - "script.garden_soft_very"
    - "script.garden_bright"

state_home:
  name: State home
  options:
    - "script.home_off"
    - "script.home_soft"
    - "script.home_soft_very"
    - "script.home_bright"
    - "script.home_bedtime"

state_garden_override:
  name: State garden override
  options:
    - "none"
    - "script.garden_security"

state_home_override:
  name: State home override
  options:
    - "none"
    - "script.home_red"
