- id: '1780691225145'
  alias: Lights - bedtime
  description: ''
  triggers:
  - trigger: time
    at: '22:00:00'
  conditions: []
  actions:
  - action: input_select.select_option
    metadata: {}
    target:
      entity_id: input_select.state_home
    data:
      option: script.home_bedtime
  mode: single
- id: '1782311824634'
  alias: Knob - single click
  description: ''
  triggers:
  - trigger: mqtt
    options:
      topic: zigbee2mqtt/Physical knob/action
      payload: single
  actions:
  - action: input_select.select_option
    metadata: {}
    target:
      entity_id: input_select.state_home
    data:
      option: script.home_soft
  - action: input_select.select_option
    metadata: {}
    target:
      entity_id: input_select.state_garden
    data:
      option: script.garden_soft
- id: '1782312884447'
  alias: Knob - double click
  description: ''
  triggers:
  - trigger: mqtt
    options:
      topic: zigbee2mqtt/Physical knob/action
      payload: double
  conditions: []
  actions:
  - action: input_select.select_option
    metadata: {}
    target:
      entity_id: input_select.state_home
    data:
      option: script.home_off
  - action: input_select.select_option
    metadata: {}
    target:
      entity_id: input_select.state_garden
    data:
      option: script.garden_off
  mode: single
- id: '1782313215704'
  alias: Knob - rotate left
  description: ''
  triggers:
  - trigger: mqtt
    options:
      topic: zigbee2mqtt/Physical knob/action
      payload: rotate_left
  conditions: []
  actions:
  - action: input_select.select_option
    metadata: {}
    target:
      entity_id: input_select.state_home
    data:
      option: script.home_soft_very
  - action: input_select.select_option
    metadata: {}
    target:
      entity_id: input_select.state_garden
    data:
      option: script.garden_soft_very
  mode: single
- id: '1782314344551'
  alias: Lights - red at night (home)
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.pir_all
    to: 'on'
  conditions:
  - condition: state
    entity_id: input_select.state_home
    state:
    - script.home_off
  - condition: sun.is_night
    options: {}
  actions:
  - action: input_select.select_option
    target:
      entity_id: input_select.state_home_override
    data:
      option: script.home_red
  - delay:
      minutes: 10
  - action: input_select.select_option
    target:
      entity_id: input_select.state_home_override
    data:
      option: none
  mode: restart
- id: '1782396257680'
  alias: Alarmo - arm away (home looks empty)
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - person.nicola_bicocchi
    - person.marzia_risi
    to:
    - not_home
    for:
      hours: 0
      minutes: 0
      seconds: 0
  - trigger: state
    entity_id:
    - binary_sensor.pir_recent_motion
    to:
    - 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 0
  conditions:
  - condition: state
    entity_id: person.nicola_bicocchi
    state:
    - not_home
    for:
      hours: 0
      minutes: 0
      seconds: 0
  - condition: state
    entity_id: person.marzia_risi
    state:
    - not_home
    for:
      hours: 0
      minutes: 0
      seconds: 0
  - condition: state
    entity_id: binary_sensor.pir_recent_motion
    state:
    - 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 0
  - condition: state
    entity_id: alarm_control_panel.alarmo
    state:
    - armed_home
    - disarmed
  actions:
  - action: alarm_control_panel.alarm_arm_away
    target:
      entity_id: alarm_control_panel.alarmo
  mode: single
- id: '1782689779297'
  alias: Alarmo - arm home (someone comes back)
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - person.nicola_bicocchi
    - person.marzia_risi
    to: home
  conditions:
  - condition: state
    entity_id: alarm_control_panel.alarmo
    state: armed_away
  actions:
  - action: alarm_control_panel.alarm_disarm
    metadata: {}
    target:
      entity_id: alarm_control_panel.alarmo
    data: {}
  mode: single
- id: '1784049262902'
  alias: Lights - off late night (home)
  description: ''
  triggers:
  - trigger: time
    at: 02:00:00
  conditions: []
  actions:
  - action: input_select.select_option
    target:
      entity_id: input_select.state_home
    data:
      option: script.home_off
  mode: single
- id: '1784117377964'
  alias: Lights - on at sunset (home)
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id: sensor.light_sensor_illuminance
    for:
      hours: 0
      minutes: 5
      seconds: 0
    below: 900
  conditions:
  - condition: sun
    before: sunset
    after: sunset
    after_offset:
      hours: -3
      minutes: 0
      seconds: 0
  - condition: state
    entity_id: input_select.state_home
    state: script.home_off
  actions:
  - action: input_select.select_option
    target:
      entity_id: input_select.state_home
    data:
      option: script.home_soft
  mode: single
- id: '1784138757054'
  alias: Alarmo - disarm (at sunrise)
  description: ''
  triggers:
  - trigger: sun
    event: sunrise
    offset: 0
  conditions: []
  actions:
  - condition: state
    state:
    - armed_home
    entity_id: alarm_control_panel.alarmo
  - action: alarm_control_panel.alarm_disarm
    metadata: {}
    target:
      entity_id: alarm_control_panel.alarmo
    data: {}
  mode: single
- id: '1785015944438'
  alias: Knob - rotate right
  description: ''
  triggers:
  - trigger: mqtt
    options:
      topic: zigbee2mqtt/Physical knob/action
      payload: rotate_right
  conditions: []
  actions:
  - action: input_select.select_option
    metadata: {}
    target:
      entity_id: input_select.state_home
    data:
      option: script.home_bright
  - action: input_select.select_option
    metadata: {}
    target:
      entity_id: input_select.state_garden
    data:
      option: script.garden_bright
  mode: single
- id: '1785016710621'
  alias: Alarm - arm home (at night)
  description: ''
  triggers:
  - trigger: time
    at: 00:00:00
  conditions: []
  actions:
  - condition: state
    state:
    - disarmed
    entity_id: alarm_control_panel.alarmo
  - action: alarm_control_panel.alarm_arm_home
    metadata: {}
    target:
      entity_id: alarm_control_panel.alarmo
    data: {}
  mode: single
- id: '1785281663953'
  alias: Heater - increment daily cycles
  description: ''
  triggers:
  - trigger: switch.turned_on
    target:
      entity_id: switch.heater_switch
    options:
      behavior: each
      for: 00:00:00
  conditions: []
  actions:
  - action: counter.increment
    metadata: {}
    target:
      entity_id: counter.heater_start_count_24h
    data: {}
  mode: single
- id: '1785439809293'
  alias: Heater - reset daily cycles
  description: ''
  triggers:
  - trigger: time
    at: 00:00:00
  conditions: []
  actions:
  - action: counter.reset
    metadata: {}
    target:
      entity_id: counter.heater_start_count_24h
    data: {}
  mode: single
- id: '1785869283532'
  alias: Lights - on at sunset (garden)
  description: ''
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.light_sensor_illuminance
    for:
      hours: 0
      minutes: 5
      seconds: 0
    below: 150
  conditions:
  - condition: sun
    before: sunset
    after: sunset
    after_offset:
      hours: -3
      minutes: 0
      seconds: 0
    before_offset:
      hours: 1
      minutes: 0
      seconds: 0
  - condition: state
    entity_id: input_select.state_garden
    state: script.garden_off
  actions:
  - action: input_select.select_option
    target:
      entity_id: input_select.state_garden
    data:
      option: script.garden_soft
  mode: single
- id: '1786810352721'
  alias: Apply state - home
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - input_select.state_home
    - input_select.state_home_override
  actions:
  - action: script.home_apply
    data: {}
  mode: single
- id: '1786810585709'
  alias: Apply state - garden
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - input_select.state_garden
    - input_select.state_garden_override
  actions:
  - action: script.garden_apply
  mode: single
- id: '1786827072049'
  alias: Lights - off late night (garden)
  description: ''
  triggers:
  - trigger: time
    at: 02:01:00
  conditions: []
  actions:
  - action: input_select.select_option
    target:
      entity_id: input_select.state_garden
    data:
      option: script.garden_off
  mode: single
- id: '1786827506449'
  alias: Lights - bedtime (late)
  description: ''
  triggers:
  - trigger: time
    at: '23:00:00'
  conditions: []
  actions:
  - action: input_select.select_option
    metadata: {}
    data:
      option: script.home_soft_very
    target:
      entity_id: input_select.state_home
  mode: single
