mqtt:
  host: mosquitto
  topic_prefix: frigate

detectors:
  cpu:
    type: cpu
    
go2rtc:
  streams:
    tapo_main: rtsp://nicola:episteme@192.168.1.158:554/stream1
    tapo_sub: rtsp://nicola:episteme@192.168.1.158:554/stream2

record:
  enabled: true
  detections:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 7
      mode: motion

snapshots:
  enabled: true

objects:
  track:
    - person
    - car
    - truck
    - dog
    - cat

cameras:
  tapo_c210:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/tapo_sub
          roles:
            - detect

        - path: rtsp://127.0.0.1:8554/tapo_main
          roles:
            - record

    detect:
      enabled: true
      width: 640
      height: 360
      fps: 3

version: 0.17-0
