mqtt:
  host: mosquitto

detectors:
  cpu1:
    type: cpu

go2rtc:
  streams:
    tapo_main: rtsp://nicola:episteme@192.168.1.158:554/stream1
    tapo_sub: rtsp://nicola:episteme@192.168.1.158:554/stream2

ffmpeg:
  hwaccel_args: preset-intel-vaapi

cameras:
  tapo_c210:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/tapo_sub
          roles:
            - detect

        - path: rtsp://127.0.0.1:8554/tapo_main
          roles:
            - record

    detect:
      width: 1920
      height: 1080
      fps: 5

    objects:
      track:
        - person
        - car
        - truck
        - bus
        - motorcycle
        - dog
        - cat

    record:
      enabled: true
      retain:
        days: 1

record:
  enabled: true
  retain:
    days: 1
  events:
    retain:
      default: 7

version: 0.14