mqtt:
  host: mosquitto
  topic_prefix: frigate

detectors:
  ov:
    type: openvino
    device: CPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

go2rtc:
  rtsp:
    listen: ":8554"

  streams:
    #tapo_main: rtsp://nicola:episteme@192.168.1.158:554/stream1
    #tapo_sub: rtsp://nicola:episteme@192.168.1.158:554/stream2

    annke_main: rtsp://admin:C%24utg04bkqD-L4O@192.168.1.103:554/Streaming/Channels/101
    annke_sub: rtsp://admin:C%24utg04bkqD-L4O@192.168.1.103:554/Streaming/Channels/102

record:
  enabled: true
  continuous:
    days: 0
  preview:
    # Optional: Quality of recording preview (default: shown below).
    # Options are: very_low, low, medium, high, very_high
    quality: medium
  alerts:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 7
      mode: active_objects
  detections:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 7
      mode: all

snapshots:
  enabled: True
  retain:
    default: 7

objects:
  track:
    - person
    - car
    - truck
    - motorcycle
    - bus

cameras:

  annke:
    ffmpeg:
      hwaccel_args: preset-vaapi
      inputs:
        - path: rtsp://127.0.0.1:8554/annke_sub
          roles:
            - detect

        - path: rtsp://127.0.0.1:8554/annke_main
          roles:
            - record

    motion:
      threshold: 20
      contour_area: 20
      improve_contrast: true
      mask: 0,0.533,1,0.5,1,0,0,0
    
    detect:
      enabled: true
      width: 960
      height: 432
      fps: 10

    zones:
      garden:
        coordinates: 0,0.557,1,0.528,1,1,0,1
        loitering_time: 0
        friendly_name: Garden
        inertia: 3

version: 0.17-0
